### ISSUE TITLE
v1.1.1 Release not deployed to forge

### ISSUE THREAD

**Issue by skylt** [EncoreTechnologies/puppet-fluentd#19]
21 days ago, the v1.1.1 release was tagged, however this version is not available on https://forge.puppet.com/modules/encore/fluentd/readme .
@nmaludy could you please look into this ?

**Comment by nmaludy** [comment]
@skylt looks like for some reason the github actions workflow didn't run for that tag... there's no way for me to manually run the workflow for a given tag, so i made a new release `v1.1.2` that is now live on the forge.

good find and thank you!
